first commit
pribytkovskiy/library pull request #1
Opened 2018-11-08 15:56 UTC by pribytkovskiy

2018-11-13 17:58 UTC, 6aBblKuH commented on .rubocop.yml
> +FileName:
remove

2018-11-13 17:58 UTC, 6aBblKuH commented on model/Author.rb
> +    @name = params[0][0]
redo

2018-11-13 17:58 UTC, 6aBblKuH commented on model/Library.rb
> +  def save
useless

2018-11-13 17:58 UTC, 6aBblKuH commented on model/Library.rb
> +    @book = add_book(@author)
u should only set entity

2018-11-13 17:58 UTC, 6aBblKuH commented on model/Reader.rb
> +    %w(name, email, city, street).each { |param| instance_eval("Validation.check_string(@#{param})") }
```ruby
[@name, @email].each(&method(:Validation.method(:check_string)))
```

2018-11-13 17:58 UTC, 6aBblKuH commented on modules/Statistic.rb
> +    @order.group_by(&:"#{param_sort}").sort_by { |_, order| order.size }.reverse
use ```-order.size``` for excluding ```reverse```

2018-11-13 17:58 UTC, 6aBblKuH commented on modules/Statistic.rb
> +  def group_sort(param_sort)
validate ```param_sort```

2018-11-13 17:58 UTC, 6aBblKuH commented on modules/Statistic.rb
> +    group_sort('book').take(popular_book_count).map { |array| array[1] }.flatten.map(&:reader).uniq.size
try to redo without flatten and calling some position of array

2018-11-13 17:58 UTC, 6aBblKuH commented on modules/Validation.rb
> +  class MyCustomError < StandardError
rename please

2018-11-13 17:58 UTC, 6aBblKuH commented on modules/Validation.rb
> +    attr_reader :object
remove

2018-11-13 17:58 UTC, 6aBblKuH commented on modules/Validation.rb
> +module Validation
redo to different errors

2018-11-15 17:16 UTC, dzemlianoi-double commented on index.rb
> +library.random_add
it shouldn't be the method of library

2018-11-15 17:16 UTC, dzemlianoi-double commented on model/author.rb
> +    StringError.new.check_string(@name)
try to rethink

2018-11-15 17:16 UTC, dzemlianoi-double commented on modules/initialize.rb
> +module Initialize
separate class - Generator - not module

2018-11-15 17:16 UTC, dzemlianoi-double commented on modules/statistic.rb
> +    return if (param_sort != 'reader') && (param_sort != 'book')
constants + array check

2018-11-15 17:16 UTC, dzemlianoi-double commented on modules/statistic.rb
> +  def group_sort(param_sort)
private

2018-11-15 17:16 UTC, dzemlianoi-double commented on modules/statistic.rb
> +    @orders.first.group_by(&:"#{param_sort}").sort_by { |_, order| -order.size }
you mustn't use instance variables into modules

2018-11-15 17:16 UTC, dzemlianoi-double commented on modules/statistic.rb
> +    group_sort('reader').map { |reader_orders| reader_orders.first }.take(popular_readers)
use symbols

2018-11-15 17:16 UTC, dzemlianoi-double commented on modules/statistic.rb
> +    group_sort('reader').map { |reader_orders| reader_orders.first }.take(popular_readers)
move it to group_sort

2018-11-15 17:16 UTC, dzemlianoi-double commented on modules/statistic.rb
> +  def readers_three_most_popular_books(popular_book_count = 3)
rethink logic

2018-11-15 17:16 UTC, dzemlianoi-double commented on modules/uploader.rb
> +  def load
don't use coupling of module and class

2018-11-15 17:16 UTC, dzemlianoi-double commented on modules/uploader.rb
> +    File.open('./data/readers.yml', 'w') { |file| file.write(readers.to_yaml) }
constants and DRY

2018-11-15 17:16 UTC, dzemlianoi-double commented on modules/validation.rb
> +      raise WrongClassError.new(object, klass), "Object not instance of of #{object}!" unless object.is_a? klass
redone

2018-11-22 07:44 UTC, bezrukavyi requested changes

2018-11-22 07:44 UTC, bezrukavyi commented on .fasterer.yml
> +  - 'db/schema.rb'
I think, you don't have this directory

2018-11-22 07:44 UTC, bezrukavyi commented on modules/generator.rb
> +  def random_add(obj)
Will be better, to rename `obj` to `library`, because you don't have any another object with the same behaviour

2018-11-22 07:44 UTC, bezrukavyi commented on modules/statistic.rb
> +    popular_orders.flatten.map(&:reader).uniq.size
Maybe better to receive `reader` when you are mapping `book orders`. So you can decrease count of iterations

```ruby
popular_readers = group_sort(orders, :book).take(popular_book_count).map { |book_orders| book_orders[1].reader }
popular_readers.flatten.uniq.size
```

2018-11-22 07:46 UTC, bezrukavyi commented on modules/constants.rb
> +CLASS_NAME = %i[book reader author order].freeze
It's strange. Constants need to define where they will be used

2018-11-22 08:23 UTC, pribytkovskiy commented on modules/statistic.rb
> +    popular_orders.flatten.map(&:reader).uniq.size
book_orders[1] - array orders most popular book
popular_readers = group_sort(orders, :book).take(popular_book_count).map { |book_orders| book_orders[1].map(&:reader) }
popular_readers.flatten.uniq.size

2018-12-01 21:45 UTC, merged